### ISSUE TITLE
Clear Scene Cache works only when switching scene afterwards

### ISSUE THREAD

**Issue by johaenns** [SCIInstitute/Duality_iosFrontend#18]
When hitting "Clear Scene Cache", going to "Select Scene" afterwards (without any action) and then going to "3D View", the old scene is still shown.

When selecting a different scene in "Select Scene" in between (and directly switching back), it works.

**Comment by david-mccann** [comment]
data sets are now reloaded when switching back to a view after the cache has been cleared.
